### ISSUE TITLE
Add buttons instead of confirm queries

### ISSUE THREAD

**Issue by CodeMyGame1** [aaditisawesome/aaditshangmanbot#6]
When requiring the user to confirm something (such as creating or deleting their account), display a button that they can click to agree, instead of them passing a "confirm" query to the `/create-account` slash command (for example).

**Comment by aaditisawesome** [comment]
Done. I have added it in the `buttons-tictactoe` branch, which will be merged soon.

**Comment by CodeMyGame1** [comment]
Reopened; will close this issue again when linked pull request is merged.

**Comment by aaditisawesome** [comment]
kk
