### ISSUE TITLE
Reword Privacy Policy

### ISSUE THREAD

**Issue by CodeMyGame1** [aaditisawesome/aaditshangmanbot#8]
Reword the privacy policy of the bot, to make it clearer and specific

**Comment by CodeMyGame1** [comment]
Resoling this issue includes updating the Privacy Policy document to reflect changes in the privacy policy

**Comment by aaditisawesome** [comment]
I think I had accidentally linked a google docs document for the privacy policy. The actual one can be found in the README.md for this repo

**Comment by aaditisawesome** [comment]
Closing this because the google docs that I had linked earlier was by accident. Official privacy policy is on the `README.md` file of this repo.
